name: ci # The name of the pipeline

on: # Decides what the trigger for the pipeline should be. Pull requests from feature branch to main
  pull_request:
    branches: [main]

jobs:
  tests: # The name of the first job
    name: Tests
    runs-on: ubuntu-latest

    steps: # Steps for the tests job
      - name: Check out code # Checks out the code in the repository to the runner (agent)
        uses: actions/checkout@v4

      - name: Set up Go # Installs Go on the runner with a selected version
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: go test # Runs Go test on the repository
        run: go test -cover ./...

      - name: Install gosec # Install Go Security
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec # Runs Gosec on the repository
        run: gosec ./...

  styles:
    name: Style # The name of the second job
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: print Go version # Prints the version of Go
        run: go version

      - name: list files # Lists all files in the current directory
        run: ls -la

      - name: Go format # Checks the Go code for formatting errors
        run: test -z $(go fmt ./...)

      - name: Install staticcheck # Installs staticcheck on the runner
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run staticcheck # Runs staticcheck on the repository
        run: staticcheck ./...
